config/routes.rb
CaudalieBeautygrows::Application.routes.draw do
  devise_for :users

  resources :photos do
    put 'approve', :approve, on: :collection
  end

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, Photo
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  resourcify

  attr_accessible :approved, :instagram_id, :standard_url, :thumb_url, 
    :caption_text, :user_username, :user_full_name, :user_profile_picture
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @instagram = Instagram.user_recent_media("23472277", {:count => 5})
    # @instagram = Instagram.tag_recent_media('awesome', {count: 30})
    @photos = Photo.last(43).reverse
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]

  # GET /photos
  # GET /photos.json
  def index
    if params[:approved] == "true"
      @photos = Photo.where("approved = ?", true)
    else
      @instagram_photos = Instagram.tag_recent_media('beautygrows', {count: 30})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def approve
    approved_photos = params[:approved_photos]
    instagram_photos = params[:photos]
    instagram_photos.each do |instagram_photo|
      existing_photo = Photo.find_by_instagram_id instagram_photo[:instagram_id]
      if approved_photos.include? instagram_photo[:instagram_id] and !existing_photo
        photo = Photo.new(
          instagram_id: instagram_photo[:instagram_id],
          standard_url: instagram_photo[:standard_url],
          thumb_url: instagram_photo[:thumb_url],
          caption_text: instagram_photo[:caption_text],
          user_username: instagram_photo[:user_username],
          user_full_name: instagram_photo[:user_full_name],
          user_profile_picture: instagram_photo[:user_profile_picture],
          approved: true
        )
        photo.save
      elsif existing_photo and !(approved_photos.include? existing_photo.instagram_id)
        existing_photo.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to photos_path(approved: true) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaudalieBeautygrows</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instagram_id %><br />
    <%= f.text_field :instagram_id %>
  </div>
  <div class="field">
    <%= f.label :standard_url %><br />
    <%= f.text_field :standard_url %>
  </div>
  <div class="field">
    <%= f.label :thumb_url %><br />
    <%= f.text_field :thumb_url %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% if current_user and can? :manage, :photo %>
  <% if @instagram_photos %>
  <table>
    <tr>
      <th>Approved</th>
      <th></th>
    </tr>
    <%= form_tag approve_photos_path, method: :put do %>
      <% @instagram_photos.each do |photo| %>
        <tr>
          <% instagram_thumbnail_url = photo.images.thumbnail.url %>
          <% instagram_standard_url = photo.images.standard_resolution.url %>
          <td><%= check_box_tag "approved_photos[]", photo.id %></td>
          <td><%= image_tag instagram_thumbnail_url %></td>
          <%= hidden_field_tag "photos[][instagram_id]", photo.id %>
          <%= hidden_field_tag "photos[][standard_url]", instagram_standard_url %>
          <%= hidden_field_tag "photos[][thumb_url]", instagram_thumbnail_url %>
          <%= hidden_field_tag "photos[][caption_text]", photo.caption.text %>
          <%= hidden_field_tag "photos[][user_username]", photo.user.username %>
          <%= hidden_field_tag "photos[][user_full_name]", photo.user.full_name %>
          <%= hidden_field_tag "photos[][user_profile_picture]", photo.user.profile_picture %>
        </tr>
      <% end %>
      <tr>
        <td><%= submit_tag "Submit" %></td>
        <td></td>
      </tr>
    <% end %>
  </table>
  <% elsif @photos %>
    <table>
      <tr>
        <th>Approved</th>
        <th></th>
      </tr>
      <%= form_tag approve_photos_path, method: :put do %>
        <% @photos.each do |photo| %>
          <tr>
            <td><%= check_box_tag "approved_photos[]", photo.instagram_id, true %></td>
            <td><%= image_tag photo.thumb_url %></td>
            <%= hidden_field_tag "photos[][instagram_id]", photo.instagram_id %>
            <%= hidden_field_tag "photos[][standard_url]", photo.standard_url %>
            <%= hidden_field_tag "photos[][thumb_url]", photo.thumb_url %>
          </tr>
        <% end %>
        <tr>
          <td><%= submit_tag "Submit" %></td>
          <td></td>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Instagram:</b>
  <%= @photo.instagram_id %>
</p>

<p>
  <b>Standard url:</b>
  <%= @photo.standard_url %>
</p>

<p>
  <b>Thumb url:</b>
  <%= @photo.thumb_url %>
</p>

<p>
  <b>Approved:</b>
  <%= @photo.approved %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>